---
maven/apache-maven-3.3.3-bin.tar.gz:
  object_id: 092d9f7f-c27d-4dbe-96d5-39269bc41887
  sha: c8f257dce3381d9d8c420168a6df0fa25664337c
  size: 8042383
openjdk/jdk-8u72-ea-bin-b02-linux-x64-13_oct_2015.tar.gz:
  object_id: a179a758-077e-40d3-b2bd-4468f22e34b0
  sha: dc75d18b76b6a7666d738f503dc44fae8483e37f
  size: 126378270
